neural_field_type: gs
expname: ${neural_field_type}_${task}_${dataset.name}_${dataset.scene}
task: novel_view_synthesis
seed: 42

dataset:
  name: aerial
  root_dir: /home/usr/datasets/${dataset.name}
  scene: ["building", "rubble", "Campus", "Residence", "Sci-Art"]
  train_split: train
  val_split: val
  data_split_json: ""
  factor: 4
  val_interval: 100
  apply_mask: false
  multi_blocks: true
  num_blocks: 1
  mx: 2
  my: 2
  bbox_scale_factor: [1.4,1.4,1.4]
  use_manhattan_world: true
  scale: false # urban3d scenes are aligned with ground plane under the manhattan world assumption
  rotate: false # urban3d scenes are aligned with ground plane under the manhattan world assumption
  batch_over_images: false

trainer:
  max_iterations: 80000
  ckpt_path: ""
  no_load_opt: false
  no_load_scheduler: false
  enable_tensorboard: true
  enable_visdom: false
  visdom_server:
  visdom_port:
  n_tensorboard: 100
  n_validation: 20000
  n_checkpoint: 20000
  distributed: true
  excluded_gpus: []
  num_workers: 3
  local_rank: 0
  admm:
    enable: true
    consensus_interval: 200
    alpha_xyz: 1e5
    alpha_fdc: 1e4
    alpha_fr: 1e5
    alpha_s: 1e4
    alpha_q: 1e5
    alpha_o: 1e4
    stop_adapt_iter: 32000
    mu: 10
    tau_inc: 2
    tau_dec: 2
    over_relaxation_coeff: 0.5

prune:
  iterations: [29800] # [12000, 24000]
  v_pow: 0.1
  prune_decay: 0.6
  prune_percent: 0.25

optimizer:
  lr:
    # Gaussian centers related.
    position_init: 0.000016
    position_final: 0.00000016
    position_delay_mult: 0.01
    position_max_iterations: 30000
    # Exposure related.
    exposure_lr_init: 0.01
    exposure_lr_final: 0.001
    exposure_lr_delay_steps: 0
    exposure_lr_delay_mult: 0
    exposure_max_iterations: ${trainer.max_iterations}
    # Other 3D GS properties.
    feature: 0.0025
    opacity: 0.05
    scaling: 0.005
    quaternion: 0.001
    # Decoupled appearance encoding.
    mask: 0.001

geometry:
  percent_dense: 0.001
  depth_threshold: 0.23
  coarse-to-fine: false
  sample_more_high_resolution: false
  densify_start_iter: 1000
  densify_end_iter: 30000
  densification_interval: 200
  opacity_reset_interval: 3000
  densify_grad_threshold: 0.0002
  mask: true

texture:
  max_sh_degree: 3
  anti_aliasing: false

appearance:
  use_trained_exposure: false

pipeline:
  convert_SHs_python: false
  compute_cov3D_python: false
  debug: false

loss:
  lambda_dssim: 0.2
  lambda_scale: 0.05
  lambda_mask: 0.5